services:
  - type: web
    name: magic-english-api
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: magic-english-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: magic-english-db
    plan: free
    region: singapore
